name: CD

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Add go to path
      run: echo "/usr/local/go/bin" >> $GITHUB_PATH

    - name: Build
      run: go build -v ./...
        
    - name: Deploy
      run: cp ./mail-api /opt/golang-api/
