name: CD

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Add go to path
      run: echo "/usr/local/go/bin" >> $GITHUB_PATH

    - name: Build
      run: go build -v ./...
      
    - name: Deploy
      uses: appleboy/scp-action@v0.1.1
      with:
        host: four.garin.xyz
        username: pi
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: "mail-api"
        target: "/opt/golang-api/"
