name: CD

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Add go to path
      run: echo "/usr/local/go/bin" >> $GITHUB_PATH

    - name: Build
      run: go build -v ./...
      
    - name: Dump ssh key
      run: echo "${{ secrets.DEPLOY_SSH_KEY }}" > key
        
    - name: Deploy
      run: scp -i ./key ./mail-api pi@four.garin.xyz:/opt/golang-api/
