name: CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...
      
    - name: Env file setup
      run: touch .env

    - name: Test
      run: go test -v ./...
